- name: Creates file
  file:
    path: /usr/share/nginx/html/test.php
    state: touch
- name: Ansible create file with content example
  copy:
    dest: "/usr/share/nginx/html/example.php"
    content: |
       <?php
	$servername   = "localhost";
	$database = "";
	$username = "truonglong";
	$password = "123456";

	// Create connection
	$conn = new mysqli($servername, $username, $password);
	// Check connection
	if ($conn->connect_error) {
	   die("Connection failed: " . $conn->connect_error);
	}
	  echo "Connected successfully";
	?>
